build: off

install:
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe

skip_tags: true
clone_folder: "c:\\stack"

environment:
  global:
    STACK_ROOT: "c:\\sr"
    APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"
    
cache:
- "C:\\sr"

test_script:
- stack setup --no-terminal > nul
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack --no-terminal test

build_script:
- stack setup --no-terminal > nul
- stack build --only-snapshot --no-terminal
- stack --local-bin-path . install ffs

artifacts:
- path: ffs.exe

deploy:
  - provider: GitHub
    artifact: ffs.exe
    auth_token: ZiJ5GrxLQD85GZL+z4kUNSB6/GL6A4QqqcPXAUdG2JP3yimsG4QnPeztIZlmtZHxs6tAQfHM56TUMDeaO6dlWPpbCG5qOoQBzm3HLYBKfbJHVC08dMPzb/WMx27d87zlAP7zenhWpBqCn3q5VTSrN0lWsNfJv/jtjKuCNDuyzgP/vCZrpGgVnzALYQaiEuMjnD0e96vR0q1uxNwj38m2jKfnXIh9E6y+fiE5m7qhOthybLjLY9poaaq4/mUmv2Letpaz3mXA/vOjGkR1g/TXBatnDR2HgExh0+1yTusl5w821q0M4oIsbIjxLxAxRd7mB8yGM84v0lKpEFHUrKdWd5R6anvoCFAcLTdsmhBIB/EoGOkX/Re05s4YO16u5lyxcVklTMv/ujJkwTgIXf6HzudZ/xbTGVbeJ88Viu8BPuYwi/Why75Sxi8Jm141ye/bU9VNB0JVSXydygMF5aNHflAOTtNju3BNtk/+/IjM+R+/xo2Vm6IeC7IhO71OH2bSW+HokWfhdiCJThgU9tIpZGVtYtV4BJiGGAtPi5cFvvzlp4OWp01tL4hRENm3jxTWg6vPG540izJfWSOkgPWorc4h84OywOKaIJK9JErgpHgI36eOLJwx3+BX8EC7jLNQ0cuYzpCJIf2yBctC3qXdkLUEAZF54tD+QJEgpNoR0Bg=
    draft: true 
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true

